Fix docs and docker compose
filetrust/cdr-plugin-folder-to-folder pull request #248
Opened 2021-05-04 05:18 UTC by rajmbcoderx

2021-05-04 05:43 UTC, rajmbcoderx commented on .github/workflows/run-tests.yml
> -on: [push, pull_request]
@dinis-cruz-gw @DinisCruz Modified this so that we don't execute actions multiple times on same PR i.e. one for PUSH and one for PR

2021-05-04 08:53 UTC, DinisCruz requested changes

2021-05-04 08:53 UTC, DinisCruz commented on .github/workflows/run-tests.yml
> -on: [push, pull_request]
Good fix, I had spotted that

2021-05-04 08:53 UTC, DinisCruz commented on docker-compose.yaml
> +        - 'es01'
Humm, you lost the check for the service health which is needed for the logging

This needs to be fixed before the merged

2021-05-05 04:22 UTC, rajmbcoderx commented on docker-compose.yaml
> +        - 'es01'
@DinisCruz Since Docker-Compose spec 3+ doesn't support conditions for depends-on, I have used wait-for-it to ensure that the dependent service is started before the application is started.

https://docs.docker.com/compose/startup-order/

2021-05-05 09:55 UTC, DinisCruz requested changes
Also there are a number of tests failing, can you merge into this branch the latest version and see if those tests still fail?

2021-05-05 09:55 UTC, DinisCruz commented on .gitmodules
> +	url = https://github.com/matcornic/hugo-theme-learn.git
I actually did this first and then realised that we really didn't need this as main submodule, which is why I added it to the docker

2021-05-05 09:55 UTC, DinisCruz commented on website/Dockerfile
>  WORKDIR     site
I think this is better here

2021-05-05 09:55 UTC, DinisCruz commented on docker-compose.yaml
> +      command: ["./wait-for-it.sh", "es01:9200", "--", "python", "cdr_plugin_folder_to_folder/api/Server.py"]
why is this better than the 'service_healthy'?

which seems to be a better solution

2021-05-05 10:10 UTC, rajmbcoderx commented on docker-compose.yaml
> +      command: ["./wait-for-it.sh", "es01:9200", "--", "python", "cdr_plugin_folder_to_folder/api/Server.py"]
@DinisCruz service_healthy is not supported for docker-compose spec v3, it has been removed after after spec version 2. There are 2 ways to handle the service dependency:
1. Using wait-for-it https://github.com/vishnubob/wait-for-it
2. Using dockerize https://github.com/jwilder/dockerize

service_healthy was a much cleaner approach but that is not supported by docker-compose anymore.

2021-05-05 10:11 UTC, rajmbcoderx commented on .gitmodules
> +	url = https://github.com/matcornic/hugo-theme-learn.git
@DinisCruz I added this logic so that we can also publish github pages, I will try to see if I can clone this repository in github action.

2021-05-05 10:13 UTC, rajmbcoderx commented
> Also there are a number of tests failing, can you merge into this branch the latest version and see if those tests still fail?

The tests are failing because the cloud sdk endpoints are not available, should I update the endpoint to one of the endpoint that is working?

2021-05-05 18:02 UTC, DinisCruz approved these changes

2021-05-05 18:04 UTC, merged