Added some UTs, got some UTs to work, minor fixes in code
filetrust/cdr-plugin-folder-to-folder pull request #354
Opened 2021-05-16 11:56 UTC by gmuditdce

UTs added and some minor code fixes for #286

2021-05-16 15:09 UTC, ggrig requested changes

2021-05-16 15:09 UTC, ggrig commented on cdr_plugin_folder_to_folder/processing/File_Processing.py
> +            return False
Remove this - not needed here.
The function returns False only for not expected cases

2021-05-16 15:09 UTC, ggrig commented on cdr_plugin_folder_to_folder/storage/Storage.py
> +        return path_combine(self.config.hd3_location, os.path.basename(path))  # add path and convert to absolute paths
Remove this change - the function is used to obtain absolute paths to both files and folders in hd3

2021-05-16 15:29 UTC, DinisCruz commented on cdr_plugin_folder_to_folder/storage/Storage.py
> +        return path_combine(self.config.hd3_location, os.path.basename(path))  # add path and convert to absolute paths
correct

2021-05-17 05:55 UTC, gmuditdce commented on cdr_plugin_folder_to_folder/storage/Storage.py
> +        return path_combine(self.config.hd3_location, os.path.basename(path))  # add path and convert to absolute paths
@DinisCruz @ggrig 

Are there any cases apart from tests that will hit the else? I think no. If it does, and we need to use the path_combine function, it has a bug that needs to be resolved.

if path.startswith(self.config.hd1_location):
    rebuild_file_path = path.replace(self.config.hd1_location, self.config.hd3_location)
else:
    rebuild_file_path = self.storage.hd3(path)

One thing
def hd3(self, path=''):
    return path_combine(self.config.hd3_location, path)  # add path and convert to absolute paths

This is returning the same path as the input file location and rebuild is failing as src and destination files are the same file during copy of unsupported file to hd3 when save_unsupported_file_types is enabled

For the code
def hd3(self, path=''):
    return path_combine(self.config.hd3_location, path)  # add path and convert to absolute paths

When
self.config.hd3_location = /tmp/tmphqw5nar2/hd3
path = /tmp/tmpcavfwsyn.tmp

It returns
/tmp/tmpcavfwsyn.tmp

In the integration tests dir there is a test that reproduces this behaviour
def test_processBadFile(self):
    bad_file = temp_file(contents=random_text())
    metadata = self.meta_service.create_metadata(bad_file)
    endpoint = f'http://{self.sdk_server}:{self.sdk_port}'
    dir = metadata.metadata_folder_path()
    try:
        result = self.file_processing.processDirectory(endpoint=endpoint, dir=dir)
    except Exception as e:
        traceback.print_exc()
        self.fail("Should not have thrown")
    assert result == True
    metadata.load()
    assert metadata.data.get('rebuild_status') == 'The file type is not currently supported'

2021-05-17 07:49 UTC, ggrig approved these changes

2021-05-17 07:53 UTC, merged