Issue 30
filetrust/cdr-plugin-folder-to-folder pull request #393
Opened 2021-05-19 20:45 UTC by samarthdd

closes filetrust/cdr-plugin-folder-to-folder-bugs#30
close filetrust/cdr-plugin-folder-to-folder-bugs#18

2021-05-21 08:53 UTC, ggrig requested changes

2021-05-21 08:53 UTC, ggrig commented on cdr_plugin_folder_to_folder/pre_processing/Status.py
> +    VAR_DUPLICATES               = "duplicate_files"
This may conflict with https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/399
Please check. 
It may make sense to merge "change-completed-ok-issue-353" branch here

2021-05-23 15:21 UTC, DinisCruz approved these changes

2021-05-23 15:23 UTC, DinisCruz commented on cdr_plugin_folder_to_folder/pre_processing/Status.py
> +    VAR_DUPLICATES               = "duplicate_files"
This PR is merged on top of #399

2021-05-23 15:26 UTC, DinisCruz commented
@samarthdd can you fix the conflict? 
![image](https://user-images.githubusercontent.com/656739/119266645-8c416b80-bbe3-11eb-91ae-4ff6369c26c8.png)

2021-05-24 16:29 UTC, merged