File distributor tests
filetrust/cdr-plugin-folder-to-folder pull request #419
Opened 2021-05-23 16:28 UTC by gmuditdce

Added more tests to #196 
Actions run will fail, no endpoint available, need to check tomorrow

2021-05-28 04:25 UTC, ggrig requested changes

2021-05-28 04:25 UTC, ggrig commented on tests/unit/api/routes/test_File_Distributor.py
> +            traceback.print_exc()
The exception is an indication of test failure
However, with the current code, the test will pass

2021-05-28 04:25 UTC, ggrig commented on tests/unit/api/routes/test_File_Distributor.py
>          assert response.content is not None
404 is failure
Why is it considered a regular output?

2021-05-28 04:25 UTC, ggrig commented on tests/unit/api/routes/test_File_Distributor.py
>          assert response.content is not None
Same as above

2021-05-28 04:25 UTC, ggrig commented on tests/unit/metadata/test_Metadata_Service.py
> +        assert metadata.data['rebuild_status'] ==          "Initial"
Why do you check particular metadata fields only and removed comparison of the whole structure

2021-05-28 08:32 UTC, gmuditdce commented on tests/unit/api/routes/test_File_Distributor.py
>          assert response.content is not None
Hi @ggrig We are now creating 3 actual files (a pdf, a jpg and a json) and doing rebuild before testing disribution.
/hd2/data returns the todo directory that is why it is empty after processing and giving 404 and we are checking that behavior

2021-05-28 08:34 UTC, gmuditdce commented on tests/unit/metadata/test_Metadata_Service.py
> +        assert metadata.data['rebuild_status'] ==          "Initial"
Hi @ggrig We are now creating 3 actual files (a pdf, a jpg and a json) and doing rebuild before testing distribution.
Checking all fields is causing data mismatches for example in update time, creation time etc. So checking some basic stuff now should be ok?

2021-05-31 06:59 UTC, ggrig commented on tests/unit/api/routes/test_File_Distributor.py
>          assert response.content is not None
/hd2/data is outdated name of /hd2/todo
If we still have it there that should be corrected
After the correction is done, we should get 200 responses - not 404
404 must indicate test failure

2021-05-31 07:01 UTC, ggrig commented on tests/unit/metadata/test_Metadata_Service.py
> +        assert metadata.data['rebuild_status'] ==          "Initial"
By doing this we reduce the tested functionality. And this is not OK
We must find a way to include all fields there

2021-05-31 15:41 UTC, DinisCruz commented on tests/unit/metadata/test_Metadata_Service.py
> +        assert metadata.data['rebuild_status'] ==          "Initial"
I agree with @ggrig here, we need to make sure that particular scenario is taken into account

I've seen to those cases where this error fails, but this is a side effect of other tests that are not cleaning up their setup

2021-06-08 09:26 UTC, chrisdiao commented
Hello @gmuditdce , any progress on this, please?

2021-06-22 12:03 UTC, ggrig commented on tests/unit/metadata/test_Metadata_Service.py
> -                                }
This modification significanltly weakens the test
Why do we need it?

2021-06-28 08:26 UTC, chrisdiao commented
@gmuditdce , please check this PR and do all necessary changes for this to be done, please?

2021-06-28 08:59 UTC, gmuditdce commented
Need to redo this. Will add more tests after checking coveralls. Closing this for now

2021-07-15 11:47 UTC, closed without merging