Update auto_tagging.yml
filetrust/cdr-plugin-folder-to-folder pull request #453
Opened 2021-05-31 10:33 UTC by samarthdd

adding label as tag name on merging to branch

2021-05-31 15:56 UTC, DinisCruz requested changes

2021-05-31 15:56 UTC, DinisCruz commented on .github/workflows/auto_tagging.yml
> +      - name : tag PR on merge
@samarthdd can describe in detail what is the sequence of events that are supposed to happen?

2021-05-31 15:56 UTC, DinisCruz commented on .github/workflows/auto_tagging.yml
> +                  tag_name=${{ steps.tagging.outputs.tag_id }}
what is value?

is it the tag name of the PR comment?

If so when does this kick in, after the tag is added?

2021-05-31 15:56 UTC, DinisCruz commented on .github/workflows/auto_tagging.yml
> +                  color="$(openssl rand -hex 3)"
is this going to assign a random color?

if so, we need to change this to make sure the color is always the same (note how at the moment we only use one color)

2021-05-31 15:56 UTC, DinisCruz commented on .github/workflows/auto_tagging.yml
> +                  curl -X POST  -H "Accept: application/vnd.github.v3+json" -H"authorization: Bearer ${{ secrets.GITHUBPAT }}" https://api.github.com/repos/samarthdd/git-wiki-action/labels -d '{"name
is `https://api.github.com/repos/samarthdd/git-wiki-action/labels` the right repo

2021-05-31 16:04 UTC, samarthdd commented on .github/workflows/auto_tagging.yml
> +                  color="$(openssl rand -hex 3)"
YES THIS is random color now. ok i will change to one color then

2021-05-31 16:19 UTC, samarthdd commented on .github/workflows/auto_tagging.yml
> +                  curl -X POST  -H "Accept: application/vnd.github.v3+json" -H"authorization: Bearer ${{ secrets.GITHUBPAT }}" https://api.github.com/repos/samarthdd/git-wiki-action/labels -d '{"name
fixed

2021-05-31 16:19 UTC, samarthdd commented on .github/workflows/auto_tagging.yml
> +                  color="$(openssl rand -hex 3)"
changed to color="D2C3F9" which is used in other PR

2021-06-02 13:24 UTC, DinisCruz commented on .github/workflows/auto_tagging.yml
> +#       - develop
Hi, shouldn’t we still limit this to these two branches, what happens if somebody does a PR into another branch?

2021-06-02 13:24 UTC, DinisCruz approved these changes

2021-06-02 13:24 UTC, merged

2021-06-02 13:33 UTC, samarthdd commented on .github/workflows/auto_tagging.yml
> +#       - develop
Yes currently even on PR, i am checking only for develop and main branches. if PR is merged to some branch, it wont execute anything.

The run might fail while labelling PR. But I will check and verify once

2021-06-02 13:42 UTC, samarthdd commented on .github/workflows/auto_tagging.yml
> +#       - develop
ok there is some issue. I willl check this