Watch hd2 changes issue 325
filetrust/cdr-plugin-folder-to-folder pull request #471
Opened 2021-06-07 16:45 UTC by ggrig

This implements new pre-procesinng APIs that start and stop the watcher thread.
Once the watcher is started no other pre-porcessing API is allowed until the watcher is stopped.
The watcher does not interfere HD2 processing API

2021-06-09 09:28 UTC, DinisCruz requested changes
We need to do a set of performance tests on this and document the workflow changes

We also need a detailed test plan to test the changes in behaviour

2021-06-09 09:28 UTC, DinisCruz commented on cdr_plugin_folder_to_folder/pre_processing/Pre_Processor.py
> +        self.pre_processing_thread.start()
We need to check the performance implications of this

what happens when there are tons of files in HD1?

We also need a diagram for this change of workflow

2021-06-11 05:57 UTC, ggrig commented
The implications on the system performance of adding the watcher have been studied. When running on t3.xlarge EC2 instance, the feature does not add load to CPU, RAM, or phase 2 processing speed. The highest load noticed with the watcher thread running (and no phase 2 in progress) was 12.1 % on one of the CPU cores. Mostly it stays in the range from 0% to 8.1%

![image](https://user-images.githubusercontent.com/26714598/121638040-5f260180-ca9b-11eb-877b-7048e8ba65c5.png)

2021-06-11 05:57 UTC, ggrig commented
![image](https://user-images.githubusercontent.com/26714598/121638099-78c74900-ca9b-11eb-925b-bc72af5bbf6f.png)

2021-06-23 12:51 UTC, merged