Configure_env test coverage improvements - issue 504
filetrust/cdr-plugin-folder-to-folder pull request #505
Opened 2021-06-15 15:45 UTC by ggrig

ISSUE
- #504

2021-06-22 13:39 UTC, chrisdiao commented
Hello @gmuditdce and @rajmbcoderx , could you please have a code review for this PR, please?

cc: @GINAGC

2021-06-23 17:23 UTC, gmuditdce requested changes

2021-06-25 08:46 UTC, ggrig commented on tests/unit/configure/test_Configure_Env_core.py
> +    # @pytest.mark.skip("this is breaking current .env file (this needs to run on a temp .env file)")
@gmuditdce 
It is fixed and enabled. The "SKIP" clause is commented out

It was skipped previously because of :
"this is breaking current .env file (this needs to run on a temp .env file)"

2021-06-30 09:37 UTC, chrisdiao commented
@gmuditdce , could you please review this PR, please?

2021-06-30 09:57 UTC, gmuditdce approved these changes

2021-06-30 15:50 UTC, merged