Updated terraform issues highlighted by snyk
filetrust/cdr-plugin-folder-to-folder pull request #644
Opened 2021-07-20 14:17 UTC by Girish-pingala

2021-07-21 08:57 UTC, ggrig approved these changes

2021-07-21 09:07 UTC, pranaysahith requested changes

2021-07-21 09:07 UTC, pranaysahith commented on infra/terraform/aws/modules/alb/main.tf
> +  internal           = true
This should not be internal, as the loadbalancer should be accessible from outside.

2021-07-21 12:13 UTC, chrisdiao commented
@Girish-pingala could you please:
1. Add "HOW TO TEST" information in this PR:
     UNIT TEST
    INTEGRATION TEST
    SMOKE TEST

2. Update the DOCUMENTATION - if applicable

2021-07-21 12:31 UTC, Girish-pingala commented on infra/terraform/aws/modules/alb/main.tf
> +  internal           = true
@pranaysahith Changes has been rolled back. Internal is set to false.

2021-07-22 09:36 UTC, chrisdiao commented
@Girish-pingala , could you resolve the conflict for this PR, please?

2021-07-23 10:45 UTC, pranaysahith approved these changes

2021-07-23 10:48 UTC, merged