F2F should support adding https SDK IP addresses
filetrust/cdr-plugin-folder-to-folder pull request #646
Opened 2021-07-21 03:34 UTC by rajmbcoderx

## Summary

Now F2F plugin would use HTTPS for Cloud SDK and default Cloud SDK has been changed to https://cloud-sdk.glasswallsolutions.com 

UI had been modified to use 443 as default port for cloud sdk instead of 80.

## Issue
https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/565
https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/616

2021-07-21 07:34 UTC, chrisdiao commented
@rajmbcoderx , could you please check why sonarcloud check pipeline is failing?

2021-07-21 08:35 UTC, ggrig requested changes

2021-07-21 08:35 UTC, ggrig commented on cdr_plugin_folder_to_folder/configure/Configure_Env.py
> +                server_url = "https://" + endpoint_json['Endpoints'][idx]['IP'] + ":" + \
I believe we must support both HTTP and HTTPS
With this change, we disable HTTP support

2021-07-22 08:07 UTC, gmuditdce approved these changes

2021-07-22 13:32 UTC, ggrig approved these changes

2021-07-22 13:40 UTC, merged